# Generated by Django 2.0 on 2020-02-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20200130_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_tags',
            field=models.CharField(default='#', max_length=40, verbose_name='Tags'),
        ),
    ]
